export const qk = {
  setupStatus: ['setup-status'] as const,
  me: ['me'] as const,
  version: ['meta', 'version'] as const,
  sourceSpecs: ['meta', 'sources'] as const,
  destinationSpecs: ['meta', 'destinations'] as const,
  notifierSpecs: ['meta', 'notifiers'] as const,
  tools: ['meta', 'tools'] as const,
  timezones: ['meta', 'timezones'] as const,
  dashboard: ['dashboard'] as const,
  sources: ['sources'] as const,
  source: (id: string) => ['sources', id] as const,
  destinations: ['destinations'] as const,
  destination: (id: string) => ['destinations', id] as const,
  destinationBrowse: (id: string, prefix: string) => ['destinations', id, 'browse', prefix] as const,
  jobs: ['jobs'] as const,
  job: (id: string) => ['jobs', id] as const,
  jobRuns: (id: string) => ['jobs', id, 'runs'] as const,
  jobArtifacts: (id: string) => ['jobs', id, 'artifacts'] as const,
  runs: (filters?: Record<string, unknown>) => ['runs', filters ?? {}] as const,
  run: (id: string) => ['runs', id] as const,
  artifacts: (filters?: Record<string, unknown>) => ['artifacts', filters ?? {}] as const,
  artifact: (id: string) => ['artifacts', id] as const,
  channels: ['channels'] as const,
  channel: (id: string) => ['channels', id] as const,
  settings: ['settings'] as const,
  users: ['users'] as const,
  tokens: ['tokens'] as const,
  audit: (filters?: Record<string, unknown>) => ['audit', filters ?? {}] as const,
  docsIndex: ['docs'] as const,
  docsPage: (path: string) => ['docs', 'page', path] as const,
  docsSearch: (query: string) => ['docs', 'search', query] as const,
}
